In [1]:
import torch
from torch.utils.data import Dataset, DataLoader
from random import randint

class BinDataset(Dataset):
     def __init__(self, arr=[0,1]):
         super(Dataset, self).__init__()
         self.arr = arr
         
        
     def __len__(self): # ovo se mora definirati
         return len(self.arr)
        
     def __getitem__(self, index): # i ovo za uzeti  data, truth
        tensor = torch.tensor((self.arr[index]), dtype = torch.float, requires_grad = True)
        tensor = torch.tensor((self.arr[index]), dtype = torch.float, requires_grad = False)
        return tensor.unsqueeze(0), tensor.unsqueeze(0)
#         return torch.FloatTensor(self.arr[index]), torch.FloatTensor(self.arr[index])

arr = [randint(0, 1) for p in range(0, 20)]     

# print(arr)

data_train = BinDataset(arr=arr)
data_train_loader = DataLoader(data_train, batch_size=5, shuffle=True)

# print(len(data_train), data_train[0][0])
# print(len(data_train_loader))

print(len(data_train))
# print(torch.tensor([1], dtype=torch.int).shape)
# print(torch.tensor([1], dtype=torch.int))
# print(torch.tensor(1, dtype=torch.int))
# for (x,y) in data_train:
#     print(x,y)
#     print(type(x))

20


Input size 1
hidden 3
Output size 1

When you have more than two hidden layers, the model is also called the deep/multilayer feedforward model or multilayer perceptron model(MLP).

In [20]:
import torch
import torch.nn as nn
import torchvision.transforms.functional as TF


class Network(nn.Module):
    def __init__(self, in_channels=1, out_channels=1,hidden_size=3):
        super(Network, self).__init__()
        self.fc = nn.Linear(in_channels,in_channels) # fully connected linear layer
        self.relu = torch.nn.ReLU()  # step function / activation function
        # After every hidden layer, an activation function is applied to introduce non-linearity
        self.fc1 = torch.nn.Linear(in_channels, hidden_size) # fully connected linear layer
        self.relu = torch.nn.ReLU() # step function / activation function
        self.fc2 = torch.nn.Linear(hidden_size, out_channels) # fully connected linear layer
        self.sigmoid = torch.nn.Sigmoid() # step function / activation function
        
    def forward(self, x):
        x = self.fc(x)
#         x = self.relu(x)         
#         x = self.fc1(x)
#         x = self.relu(x)
#         x = self.fc2(x)
#         x = self.sigmoid(x)
#         print(x)
        return torch.abs(torch.round(x))


x = torch.randn((1))
model = Network(in_channels=1, out_channels=1,hidden_size=3)
preds = model(x)
print(preds.shape)
print(x.shape)
assert x.shape == preds.shape
print(x,preds)


torch.Size([1])
torch.Size([1])
tensor([0.4253]) tensor([0.], grad_fn=<AbsBackward>)


Training

In [22]:
from tqdm import tqdm

model = Network(1, 1, 3)
criterion = torch.nn.SoftMarginLoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

model.eval() # sets the PyTorch module to evaluation mode
# We want to do this because we don’t want the model to learn new weights
# when we just want to check the loss before training. 
# To train, we switch the mode back to training mode.
# y_pred = model(data_train[0][0])
# print(y_pred)
# print(loss(data_train[0][0],data_train[0][1]))
# before_train = loss(y_pred.squeeze(), data_train[0][0].squeeze())
# print('Test loss before training' , before_train.item())

model.train()

loop = tqdm(data_train_loader)
for idx, (x, y) in enumerate(loop):
    optimizer.zero_grad()
    y_pred = model(x)
    loss = criterion(y_pred, y)
#     print(y_pred, y)
    print('Epoch {}: train loss: {}'.format(idx, loss.item()))
    loss.backward()
    optimizer.step()
    


100%|██████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 1999.19it/s]

Epoch 0: train loss: 0.5411929488182068
Epoch 1: train loss: 0.6171700358390808
Epoch 2: train loss: 0.5411929488182068
Epoch 3: train loss: 0.38923874497413635


In [29]:
model.eval()
n = torch.randint(0,2,(1,), dtype = torch.float, requires_grad = False)
print(model(n),n)

tensor([1.], grad_fn=<AbsBackward>) tensor([0.])


In [5]:
from sklearn.datasets import make_blobs
import torch
import numpy

def blob_label(y, label, loc): # assign labels
    target = numpy.copy(y)
    for l in loc:
        target[y == l] = label
    return target
x_train, y_train = make_blobs(n_samples=40, n_features=2, cluster_std=1.5, shuffle=True)
x_train = torch.FloatTensor(x_train)
y_train = torch.FloatTensor(blob_label(y_train, 0, [0]))
y_train = torch.FloatTensor(blob_label(y_train, 1, [1,2,3]))
x_test, y_test = make_blobs(n_samples=10, n_features=2, cluster_std=1.5, shuffle=True)
x_test = torch.FloatTensor(x_test)
y_test = torch.FloatTensor(blob_label(y_test, 0, [0]))
y_test = torch.FloatTensor(blob_label(y_test, 1, [1,2,3]))

print(x_train[0])

tensor([0.1031, 7.3371])


In [127]:
m = nn.Sigmoid()
n = torch.randint(0,2,(1,))
print(n)
print(torch.sign(n))
n = torch.randn(1)
print(m(n),n, torch.sign(n))

tensor([1])
tensor([1])
tensor([0.4343]) tensor([-0.2644]) tensor([-1.])
